on:
  pull_request: {}
  push: {}

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: go build
        run: |
          go build ./...
      - name: go install
        run: |
          GOBIN=$(pwd)/install go install ./...
      - name: go test
        run: |
          PATH=$PATH:$(pwd)/install go test -tags llama.runtime ./...
      - name: Check license headers
        run: |
          ./scripts/dev/check-license
