on:
  pull_request: {}
  push: {}

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.6'
      - name: go build
        run: |
          go build ./...
      - name: go test
        run: |
          go test -tags llama.runtime ./...
      - name: Check license headers
        run: |
          ./scripts/check-license
